export { default as Login } from './Login';
export { default as Products } from './Products/Products';
export { default as Register } from './Register';
export { default as OrderDetail } from './OrderDetail';
export { default as CustumeOrders } from './CustumerOrders';
export { default as Checkout } from './Checkout';
export { default as SellerOrders } from './SellerOrders';
export { default as SellerDetails } from './SellerDetails';
export { default as AdminManager } from './AdminManager';
